# ------------------------ 限流配置 ---------------------------- #
security:
  limit:
    # 是否开启限流
    enable: true
    # 限流计数策略 本地缓存cache、redis
    count-strategy: cache

spring:
  # ------------------  redis配置 ------------------#
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9090
  servlet:
    context-path: /